name: Generate Mermaid Diagram

on:
  workflow_call:
    inputs:
      code_status:
        description: "Status for Code Analysis"
        required: true
        type: string
        default: "pending"
      architecture_risk_status:
        description: "Status for Architecture Risks"
        required: true
        type: string
        default: "pending"
      penetration_testing_status:
        description: "Status for Penetration Testing"
        required: true
        type: string
        default: "pending"
      risk_based_status:
        description: "Status for Risk-Based Security Testing"
        required: true
        type: string
        default: "pending"
      abuse_case_status:
        description: "Status for Abuse Cases"
        required: true
        type: string
        default: "pending"
      security_requirements_status:
        description: "Status for Security Requirements"
        required: true
        type: string
        default: "pending"
      security_operations_status:
        description: "Status for Security Operations"
        required: true
        type: string
        default: "pending"
  workflow_dispatch:
    code_status:
      description: "Status for Code Analysis"
      required: true
      type: string
      default: "pending"
    architecture_risk_status:
      description: "Status for Architecture Risks"
      required: true
      type: string
      default: "pending"
    penetration_testing_status:
      description: "Status for Penetration Testing"
      required: true
      type: string
      default: "pending"
    risk_based_status:
      description: "Status for Risk-Based Security Testing"
      required: true
      type: string
      default: "pending"
    abuse_case_status:
      description: "Status for Abuse Cases"
      required: true
      type: string
      default: "pending"
    security_requirements_status:
      description: "Status for Security Requirements"
      required: true
      type: string
      default: "pending"
    security_operations_status:
      description: "Status for Security Operations"
      required: true
      type: string
      default: "pending"
jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Mermaid Diagram
        run: |
          # Opret Mermaid diagram koden
          DIAGRAM="graph TD
          n1[\"Pending\"]---n2[\"Success\"]---n3[\"Error\"]
          n1:::pending
          n2:::success
          n3:::error
          A[Code Analysis]:::${{ inputs.code_status }} -->B[Architecture Risks]:::${{ inputs.architecture_risk_status }}
          B -->C[Penetration Testing]:::${{ inputs.penetration_testing_status }}
          C -->D[Risk-Based Security Testing]:::${{ inputs.risk_based_status }}
          D -->E[Abuse Cases]:::${{ inputs.abuse_case_status }}
          E -->F[Security Requirements]:::${{ inputs.security_requirements_status }}
          F -->G[Security Operations]:::${{ inputs.security_operations_status }}
          
          classDef success fill:#9ff089,stroke:#237804,stroke-width:2px,rx:10px,ry:10px;
          classDef error fill:#ff7b7b,stroke:#8c0000,stroke-width:2px,rx:10px,ry:10px;
          classDef pending fill:#ffdb6d,stroke:#b59b01,stroke-width:2px,rx:10px,ry:10px;"
          
          # Konverter til base64
          ENCODED_DIAGRAM=$(echo "$DIAGRAM" | base64 -w 0)
          
          # Hent SVG fra mermaid.ink
          curl -s "https://mermaid.ink/svg/$ENCODED_DIAGRAM" -o diagram.svg
          
          # Hent også PNG versionen
          curl -s "https://mermaid.ink/img/$ENCODED_DIAGRAM" -o diagram.png
          
          # Opret også Markdown-fil til visning
          echo "# Software Security Touchpoints Status
          
          ![Software Security Touchpoints Status](diagram.svg)
          
          *Diagram automatisk genereret baseret på status fra CI/CD pipeline.*" > security-touchpoints.md

      - name: Commit diagram to repository
        run: |
          # Opret midlertidig mappe til diagrammer
          mkdir -p /tmp/diagrams
          
          # Kopier diagrammer til midlertidig mappe
          cp diagram.svg /tmp/diagrams/ || echo "Ingen diagram.svg fundet"
          cp diagram.png /tmp/diagrams/ || echo "Ingen diagram.png fundet"
          cp security-touchpoints.md /tmp/diagrams/ || echo "Ingen security-touchpoints.md fundet"
          
          # Start med et friskt repository
          cd /tmp
          git clone https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} repo
          cd repo
          
          # Sæt git konfiguration
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Opret docs mappe hvis den ikke findes
          mkdir -p docs/images
          
          # Kopier diagrammer fra midlertidig mappe
          cp /tmp/diagrams/diagram.svg docs/images/ 2>/dev/null || true
          cp /tmp/diagrams/diagram.png docs/images/ 2>/dev/null || true
          cp /tmp/diagrams/security-touchpoints.md docs/ 2>/dev/null || true
          
          # Tjek om der er ændringer
          if git status --porcelain | grep -q "docs/"; then
          # Add, commit og push
          git add docs/
          git commit -m "Opdateret software security status diagram"
          git push origin HEAD:${{ github.ref_name }}
          echo "Diagram opdateret og pushet"
          else
          echo "Ingen ændringer at committe"
          fi